included:
  - Anvil
  - Apps
  - Core
  - Features
  - Hephaestus
  - HephaestusTests
  - HephaestusUITests
  - Tests

excluded:
  - .build
  - .swiftpm
  - Hephaestus.xcodeproj
  - Hephaestus.xcworkspace
  - Proofs

cache_path: .swiftlint_cache

line_length:
  warning: 120
  error: 180
  ignores_comments: true
  ignores_urls: true
  ignores_function_declarations: true

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 40
  error: 60

indentation_width:
  indentation_width: 4
  include_comments: true
  include_compiler_directives: true
  include_multiline_strings: false

nesting:
  type_level:
    warning: 2
    error: 2
  function_level:
    warning: 4
    error: 4
  check_nesting_in_closures_and_statements: true

disabled_rules:
  - cyclomatic_complexity
  - for_where
  - function_parameter_count
  - identifier_name
  - large_tuple
  - static_over_final_class
  - trailing_comma
  - type_name
  - type_body_length

opt_in_rules:
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - empty_xctest_method
  - fatal_error_message
  - final_test_case
  - first_where
  - indentation_width
  - private_swiftui_state
  - redundant_nil_coalescing
  - sorted_first_last
  - unhandled_throwing_task
  - yoda_condition
